version: '3'
services: 
    react-app:
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "5000:3000"
        volumes: 
            - /usr/src/app/node_modules
            - .:/usr/src/app
    tests:
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes: 
            - /usr/src/app/node_modules
            - .:/usr/src/app 
        command: ["npm","run","test"]           